apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibms-core
  labels:
    app: ibms-core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ibms-core
  template:
    metadata:
      labels:
        app: ibms-core
    spec:
      containers:
      - name: frappe-backend
        image: ghcr.io/shivansh-00/ibms-core:latest
        ports:
        - containerPort: 8000
        env:
        - name: FRAPPE_SITE_NAME_HEADER
          valueFrom:
            secretKeyRef:
              name: ibms-secrets
              key: site_name
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: ibms-secrets
              key: db_host
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ibms-secrets
              key: db_password
        readinessProbe:
          httpGet:
            path: /api/method/ping
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/method/ping
            port: 8000
          initialDelaySeconds: 45
          periodSeconds: 20
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
