apiVersion: apps/v1
kind: Deployment
metadata:
  name: imbs-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: imbs-web
  template:
    metadata:
      labels:
        app: imbs-web
    spec:
      containers:
        - name: web
          image: imbs:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: imbs-web
spec:
  selector:
    app: imbs-web
  ports:
    - port: 80
      targetPort: 8000
